# SPDX-FileCopyrightText: © 2025 Nikita Krasnov <nikita.nikita.krasnov@gmail.com>
#
# SPDX-License-Identifier: MIT

name: Project's CI
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-native-x86_64:
    name: "Native build: x86_64-linux"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - name: Setup Nix
        uses: ./.github/actions/nix-setup

      - name: Build $out output
        run: |
          nix build .#packages.x86_64-linux.default
          tree result

      - name: Build $dev output
        run: |
          nix build .#packages.x86_64-linux.default.dev
          tree result-dev

      - name: Build $doc output
        run: |
          nix build .#packages.x86_64-linux.default.doc
          tree result-doc

  build-native-aarch64:
    name: "Native build: aarch64-linux"
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v5

      - name: Setup Nix
        uses: ./.github/actions/nix-setup

      - name: Build $out output
        run: |
          nix build .#packages.aarch64-linux.default
          tree result

      - name: Build $dev output
        run: |
          nix build .#packages.aarch64-linux.default.dev
          tree result-dev

      - name: Build $doc output
        run: |
          nix build .#packages.aarch64-linux.default.doc
          tree result-doc

  run-pre-commit-hooks:
    name: Run pre-commit hooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Nix
        uses: ./.github/actions/nix-setup

      - name: Configure build
        run: meson setup builddir/

      - name: Run pre-commit hooks
        run: prek run --all-files
